### ISSUE TITLE
Components not loading

### ISSUE THREAD

**Issue by berthj193** [echenley/react-router-huge-apps-refactor#2]
@echenley First, thanks for your great work.

I have successfully followed your blog post and my components are lazy-bundled from chunks.
But when I open pages on the browser, react components don't get loaded.

I have tried both of the following exports.
`module.exports = Home`
`export default class Home extends React.component`

Can you please get me a solution for this? Thanks in advance.

I have the following 3 errors.

```
warning.js?8a56:44   Warning: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

invariant.js?4599:38   Uncaught Invariant Violation: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Application.js?3d43:3   Uncaught TypeError: cb is not a function
```

**Comment by berthj193** [comment]
I'm also trying 2 approaches for `lazyLoadComponent` function in my routes.js file.
`module` vs `module.default`

```
function lazyLoadComponent (lazyModule) {
  return (location, cb) => {
    lazyModule(module => cb(null, module.default))
  }
}
```

```
function lazyLoadComponent (lazyModule) {
  return (location, cb) => {
    lazyModule(module => cb(null, module))
  }
}
```

And I'm using Redux, what could be the best approach to split and lazy load actions and reducers?
I'll highly appreciate if you outline a best structure for this.

Thanks!

**Comment by berthj193** [comment]
Wow, it has been fixed!
I have been troubleshooting with this for a couple of days, and decided to look for a help, posted error log here.
And then I realized that Application.js is also matched regex for routes which results in loading it lazily also.

For those who have trouble, use `module.default` in `lazyLoadComponent` for ES6 exports, I think this applies if you use babel 6.

@echenley Thanks for your great repo again.
Will you please post the best structure for redux apps?

**Comment by echenley** [comment]
Yes, this is true! Babel 6 had some breaking changes regarding default exports. I went through the same thing when I was learning this pattern. I'm glad you solved this.

For Redux, I am a big fan of the ["Ducks" pattern](https://github.com/erikras/ducks-modular-redux). Is this what you were thinking?

**Comment by berthj193** [comment]
@echenley Thanks, Ducks pattern seems to be much cleaner. I'll try to implement that pattern.

You mean it is possible to split and lazy load duck modules, right?
I think I can do split ducks with webpack but not sure how to lazy load ducks with `lazyLoadComponents`.
Reducers are combined altogether and used to create a big store.

It'd be very helpful if you create a new branch and let me learn from it when you get free.

Thank you!

**Comment by echenley** [comment]
I haven't ever tried to split reducers, but this looks like a good starting point: https://github.com/insin/react-examples/tree/master/code-splitting-redux-reducers. They also use the Ducks pattern, conveniently. Unfortunately the demo appears to be broken.
