### ISSUE TITLE
Regex alternative (easier?)

### ISSUE THREAD

**Issue by rosskevin** [echenley/react-router-huge-apps-refactor#4]
I found the regex to be a bit confusing and wanted to offer another that may be a bit easier to understand.  As you mention in the blog post, it has to be customized to fit the target, but I think this is inline with what you were intending (unless I am misunderstanding).

To match anything directly under a `components` directory, this should work:

``` javascript
const routeComponentRegex = /routes\/(?:.*\/)?components\/.*.js$/
```

Demo: https://regex101.com/r/cH4qH1/2

If there is an invalid/missing match, you can fork that regex demo put in the case and I'll be happy to fix it up.

**Comment by rosskevin** [comment]
FYI - currently with this regex, I see _too many_ chunks i.e. one for each component, so it isn't good as-is.  With the original regex (on OSX) my code wouldn't split and the structure is similar, so I'll have to put some more work into this.

**Comment by rosskevin** [comment]
It seems either the addition of the commons chunk plugin, or using the following query string shrinks down my chunks.  The following gives me named route chunks (without the chunks plugin):

``` javascript
loaders: [ 'bundle?lazy&name=[1]&regExp=routes\/(.*)\/components\/.*$', 'babel' ]
```

**Comment by spookshadow** [comment]
I just clone the code from github,and run , browse it in chrome , it still say --
Uncaught TypeError: Cannot call a class as a function       Course.js:4 .
any idea ?
